import json
from pathlib import Path

# Path to the JSON file containing block IDs.
DATA_JSON = Path("data.json")

# Output path for the generated function file.
OUTPUT_FILE = Path("data/datapack/function/select_block.mcfunction")

# Filter out blocks that are impossible to obtain in survival (exception: keep bedrock)
EXCLUDE_BLOCKS = {
    "air", "cave_air", "void_air", "barrier", "light", "command_block",
    "chain_command_block", "repeating_command_block", "structure_block", "jigsaw",
    "structure_void", "end_portal", "end_portal_frame", "end_gateway"
}


def main():
    if not DATA_JSON.exists():
        raise FileNotFoundError(f"{DATA_JSON} not found. Make sure the file exists and contains the block list.")

    # Load block IDs. Expecting either a list of strings or an object with a `blocks` key.
    data = json.loads(DATA_JSON.read_text())
    if isinstance(data, list):
        blocks = data
    elif isinstance(data, dict) and "blocks" in data:
        blocks = data["blocks"]
    else:
        raise ValueError("Unable to parse block list. Expected JSON array or object with 'blocks' key.")

    # Remove excluded blocks but keep bedrock even though it's unobtainable
    blocks = [b for b in blocks if b not in EXCLUDE_BLOCKS]

    # Sort and deduplicate just in case.
    blocks = sorted(set(blocks))

    total_blocks = len(blocks)

    # Generate select_block.mcfunction lines (same as before)
    lines = []
    lines.append("# Automatically generated by generate_select_block.py")
    lines.append("# DO NOT EDIT MANUALLY - run the script again if you need to refresh the list")
    lines.append(f"# Total blocks: {total_blocks}")
    lines.append("# Note: Excluded impossible-to-obtain blocks: " + ", ".join(sorted(EXCLUDE_BLOCKS)))
    lines.append("# Initializes the selected block to stone by default")
    lines.append("data modify storage datapack:temp selected_block set value \"minecraft:stone\"")
    lines.append("")

    for idx, block in enumerate(blocks):
        lines.append(
            f"execute if score #temp random_block matches {idx} run data modify storage datapack:temp selected_block set value \"minecraft:{block}\""
        )

    # Ensure output directory exists.
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    # Write to file.
    OUTPUT_FILE.write_text("\n".join(lines))

    # Update the random range in assign_random_block.mcfunction automatically
    assign_path = Path("data/datapack/function/assign_random_block.mcfunction")
    if assign_path.exists():
        assign_lines = assign_path.read_text().split("\n")
        new_range_line = f"execute store result score #temp random_block run random value 0..{total_blocks - 1}"
        assign_lines = [
            new_range_line if l.strip().startswith("execute store result score #temp random_block") or l.strip().startswith("execute store result score @s rand") else l
            for l in assign_lines
        ]
        assign_path.write_text("\n".join(assign_lines))

    print(f"Generated {OUTPUT_FILE} with {total_blocks} blocks after filtering.")
    print("Updated random range in assign_random_block.mcfunction to 0..%d" % (total_blocks - 1))
    print("Excluded blocks (kept out):", ", ".join(sorted(EXCLUDE_BLOCKS)))


if __name__ == "__main__":
    main() 